name: CMake Windows Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up build directory
      id: vars
      shell: bash
      run: echo "build-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake (Windows/MSVC)
      run: >
        cmake -B ${{ steps.vars.outputs.build-dir }}
        -DCMAKE_C_COMPILER=cl
        -DCMAKE_CXX_COMPILER=cl
        -DCMAKE_BUILD_TYPE=Release
        -S ${{ github.workspace }}

    - name: Build (Windows)
      run: cmake --build ${{ steps.vars.outputs.build-dir }} --config Release

    - name: Run Tests
      working-directory: ${{ steps.vars.outputs.build-dir }}
      run: ctest --build-config Release
